### ISSUE TITLE
Error: The specified engine (ID stable-diffusion-v1) was not found.

### ISSUE THREAD

**Issue by Zain-ul-din** [vpzomtrrfrt/stability-client#29]
I'm getting this error while using `stability-client` at `1.9.0` any idea how to fix it?

```log
C:\Users\Azra\my-stability-project>node generateImage.js
Error generating image: Error: The specified engine (ID stable-diffusion-v1) was not found.
at EventEmitter. (C:\Users\Azra\my-stability-project\node_modules\stability-client\build\index.js:1:102950)
at EventEmitter.emit (node:events:518:28)
at onEnd (C:\Users\Azra\my-stability-project\node_modules\stability-client\build\index.js:1:101241)
at C:\Users\Azra\my-stability-project\node_modules@improbable-eng\grpc-web\dist\grpc-web-client.js:1:11490
at Array.forEach ()
at e.rawOnError (C:\Users\Azra\my-stability-project\node_modules@improbable-eng\grpc-web\dist\grpc-web-client.js:1:11452)
at e.onTransportHeaders (C:\Users\Azra\my-stability-project\node_modules@improbable-eng\grpc-web\dist\grpc-web-client.js:1:9025)
at NodeHttp.responseCallback (C:\Users\Azra\my-stability-project\node_modules@improbable-eng\grpc-web-node-http-transport\lib\index.js:31:22)
at Object.onceWrapper (node:events:633:26)
at ClientRequest.emit (node:events:518:28)
```

Check Usage [here](https://github.com/Zain-ul-din/whatsapp-ai-bot/blob/master/src/models/StabilityModel.ts#L22)

**Comment by vpzomtrrfrt** [comment]
that engine is no longer available, see https://platform.stability.ai/docs/features/api-parameters#engine

**Comment by Zain-ul-din** [comment]
@vpzomtrrfrt any alternative available?

**Comment by vpzomtrrfrt** [comment]
that link lists the other options available for this API

**Comment by Zain-ul-din** [comment]
@vpzomtrrfrt Thanks! Can you update this package accordingly?
